name: "Release Build (Basic)"

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      BUILD_CONFIG: Release
      ARCHIVE_NAME: CnCNet-Spawner-${{ github.ref_name }}.zip

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        uses: ./.github/actions/build
        with:
          build-config: ${{ env.BUILD_CONFIG }}

      - name: Create an Archive for the Release
        run: |
          7z a ${{ env.ARCHIVE_NAME }} ^
          ./LICENSE.md ^
          ./${{ env.BUILD_CONFIG }}/CnCNet-Spawner.dll ^
          ./${{ env.BUILD_CONFIG }}/CnCNet-Spawner.pdb

      - name: Upload Files to the Release
        uses: softprops/action-gh-release@v2
        with:
          append_body: true
          files: ${{ env.ARCHIVE_NAME }}
