name: "Build (Non-Hardened Only)"

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: 'Build Configuration'
        required: true
        default: 'Release'
        type: choice
        options:
          - Debug
          - DevBuild
          - Release
      version:
        description: 'Version tag'
        required: false
        default: 'manual-build'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          # 不使用 SSH key，只克隆公开的子模块
          
      - name: Build
        uses: ./.github/actions/build
        with:
          build-config: ${{ github.event.inputs.build-type }}
          
      - name: Create Archive
        run: |
          7z a CnCNet-Spawner-${{ github.event.inputs.build-type }}-${{ github.event.inputs.version }}.zip ^
          LICENSE.md ^
          ${{ github.event.inputs.build-type }}/CnCNet-Spawner.dll ^
          ${{ github.event.inputs.build-type }}/CnCNet-Spawner.pdb
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CnCNet-Spawner-${{ github.event.inputs.build-type }}-${{ github.event.inputs.version }}
          path: CnCNet-Spawner-${{ github.event.inputs.build-type }}-${{ github.event.inputs.version }}.zip
